//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fri.FieldPlotService.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fri.FieldPlotService.Admin.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error has occurred..
        /// </summary>
        public static string Api_Error__1 {
            get {
                return ResourceManager.GetString("Api_Error_-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates there is a service configuration error..
        /// </summary>
        public static string Api_Error_0 {
            get {
                return ResourceManager.GetString("Api_Error_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table being requested is not available for JSON based inserts..
        /// </summary>
        public static string Api_Error_1 {
            get {
                return ResourceManager.GetString("Api_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is currently blocked from using the system..
        /// </summary>
        public static string Api_Error_11 {
            get {
                return ResourceManager.GetString("Api_Error_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor is currently blocked from using the system..
        /// </summary>
        public static string Api_Error_12 {
            get {
                return ResourceManager.GetString("Api_Error_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor was not found..
        /// </summary>
        public static string Api_Error_13 {
            get {
                return ResourceManager.GetString("Api_Error_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate username already exists in the system..
        /// </summary>
        public static string Api_Error_14 {
            get {
                return ResourceManager.GetString("Api_Error_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor user was not found..
        /// </summary>
        public static string Api_Error_15 {
            get {
                return ResourceManager.GetString("Api_Error_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor&apos;s name is invalid..
        /// </summary>
        public static string Api_Error_16 {
            get {
                return ResourceManager.GetString("Api_Error_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor code is invalid..
        /// </summary>
        public static string Api_Error_17 {
            get {
                return ResourceManager.GetString("Api_Error_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates a vendor with the same code already exists in the database..
        /// </summary>
        public static string Api_Error_18 {
            get {
                return ResourceManager.GetString("Api_Error_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor deletes are blocked if the vendor has projects in the system.  These must be removed first..
        /// </summary>
        public static string Api_Error_19 {
            get {
                return ResourceManager.GetString("Api_Error_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSN Entity cannot be null..
        /// </summary>
        public static string Api_Error_20 {
            get {
                return ResourceManager.GetString("Api_Error_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Plot Name is missing..
        /// </summary>
        public static string Api_Error_21 {
            get {
                return ResourceManager.GetString("Api_Error_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deformity ID is missing..
        /// </summary>
        public static string Api_Error_22 {
            get {
                return ResourceManager.GetString("Api_Error_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tree ID is missing..
        /// </summary>
        public static string Api_Error_23 {
            get {
                return ResourceManager.GetString("Api_Error_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project ID is missing..
        /// </summary>
        public static string Api_Error_24 {
            get {
                return ResourceManager.GetString("Api_Error_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Plot ID is missing..
        /// </summary>
        public static string Api_Error_25 {
            get {
                return ResourceManager.GetString("Api_Error_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dwd ID is missing..
        /// </summary>
        public static string Api_Error_26 {
            get {
                return ResourceManager.GetString("Api_Error_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ecosite ID is missing..
        /// </summary>
        public static string Api_Error_27 {
            get {
                return ResourceManager.GetString("Api_Error_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Person ID is missing..
        /// </summary>
        public static string Api_Error_28 {
            get {
                return ResourceManager.GetString("Api_Error_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Photo ID is missing..
        /// </summary>
        public static string Api_Error_29 {
            get {
                return ResourceManager.GetString("Api_Error_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure failed to update the records in the table..
        /// </summary>
        public static string Api_Error_3 {
            get {
                return ResourceManager.GetString("Api_Error_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Small Tree ID is missing..
        /// </summary>
        public static string Api_Error_30 {
            get {
                return ResourceManager.GetString("Api_Error_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Name is missing..
        /// </summary>
        public static string Api_Error_31 {
            get {
                return ResourceManager.GetString("Api_Error_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Small Tree Tally ID is missing..
        /// </summary>
        public static string Api_Error_32 {
            get {
                return ResourceManager.GetString("Api_Error_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Soil ID is missing..
        /// </summary>
        public static string Api_Error_33 {
            get {
                return ResourceManager.GetString("Api_Error_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stem Map ID is missing..
        /// </summary>
        public static string Api_Error_34 {
            get {
                return ResourceManager.GetString("Api_Error_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vegetation ID is missing..
        /// </summary>
        public static string Api_Error_35 {
            get {
                return ResourceManager.GetString("Api_Error_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vegetation Census ID is missing..
        /// </summary>
        public static string Api_Error_36 {
            get {
                return ResourceManager.GetString("Api_Error_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user information was not provided..
        /// </summary>
        public static string Api_Error_37 {
            get {
                return ResourceManager.GetString("Api_Error_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is missing..
        /// </summary>
        public static string Api_Error_38 {
            get {
                return ResourceManager.GetString("Api_Error_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project information is missing..
        /// </summary>
        public static string Api_Error_39 {
            get {
                return ResourceManager.GetString("Api_Error_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure failed to insert the records into the table..
        /// </summary>
        public static string Api_Error_4 {
            get {
                return ResourceManager.GetString("Api_Error_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project ID already exists..
        /// </summary>
        public static string Api_Error_40 {
            get {
                return ResourceManager.GetString("Api_Error_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project was not found..
        /// </summary>
        public static string Api_Error_41 {
            get {
                return ResourceManager.GetString("Api_Error_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSN Plot name already exists (this must be unique within the entire system)..
        /// </summary>
        public static string Api_Error_42 {
            get {
                return ResourceManager.GetString("Api_Error_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plot was not found..
        /// </summary>
        public static string Api_Error_43 {
            get {
                return ResourceManager.GetString("Api_Error_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate that an entity is missing the required ID field..
        /// </summary>
        public static string Api_Error_5 {
            get {
                return ResourceManager.GetString("Api_Error_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table already contains a record with the same ID..
        /// </summary>
        public static string Api_Error_6 {
            get {
                return ResourceManager.GetString("Api_Error_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table does not contain an existing record with the ID provided..
        /// </summary>
        public static string Api_Error_7 {
            get {
                return ResourceManager.GetString("Api_Error_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is invalid..
        /// </summary>
        public static string Api_Error_8 {
            get {
                return ResourceManager.GetString("Api_Error_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request made to backend API..
        /// </summary>
        public static string Api_Http_400 {
            get {
                return ResourceManager.GetString("Api_Http_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.  You may not have access to perform this operation based on your current role..
        /// </summary>
        public static string Api_Http_401 {
            get {
                return ResourceManager.GetString("Api_Http_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backend server appears to be down..
        /// </summary>
        public static string Api_Http_500 {
            get {
                return ResourceManager.GetString("Api_Http_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Plots Admin Tool.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Dialogs_ErrorDialog_Title {
            get {
                return ResourceManager.GetString("Dialogs_ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API error {0}: .
        /// </summary>
        public static string Error_Code {
            get {
                return ResourceManager.GetString("Error_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP error {0}: .
        /// </summary>
        public static string Error_Http {
            get {
                return ResourceManager.GetString("Error_Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string General_Active {
            get {
                return ResourceManager.GetString("General_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string General_AddProject {
            get {
                return ResourceManager.GetString("General_AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add projects to multiple vendors.
        /// </summary>
        public static string General_AddProjects {
            get {
                return ResourceManager.GetString("General_AddProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string General_AddUser {
            get {
                return ResourceManager.GetString("General_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vendor.
        /// </summary>
        public static string General_AddVendor {
            get {
                return ResourceManager.GetString("General_AddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string General_Comment {
            get {
                return ResourceManager.GetString("General_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string General_Completed {
            get {
                return ResourceManager.GetString("General_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string General_ConfirmPassword {
            get {
                return ResourceManager.GetString("General_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this project?.
        /// </summary>
        public static string General_ConfirmProjectDelete {
            get {
                return ResourceManager.GetString("General_ConfirmProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string General_ConfirmUserDelete {
            get {
                return ResourceManager.GetString("General_ConfirmUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this vendor?.
        /// </summary>
        public static string General_ConfirmVendorDelete {
            get {
                return ResourceManager.GetString("General_ConfirmVendorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        public static string General_ContactInfo {
            get {
                return ResourceManager.GetString("General_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string General_DashboardResults {
            get {
                return ResourceManager.GetString("General_DashboardResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformity information.
        /// </summary>
        public static string General_DeformityData {
            get {
                return ResourceManager.GetString("General_DeformityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string General_Deleted {
            get {
                return ResourceManager.GetString("General_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string General_Description {
            get {
                return ResourceManager.GetString("General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string General_Download {
            get {
                return ResourceManager.GetString("General_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWD information.
        /// </summary>
        public static string General_DwdData {
            get {
                return ResourceManager.GetString("General_DwdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco site information.
        /// </summary>
        public static string General_EcoSiteData {
            get {
                return ResourceManager.GetString("General_EcoSiteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string General_EndDate {
            get {
                return ResourceManager.GetString("General_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string General_FirstName {
            get {
                return ResourceManager.GetString("General_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string General_Greeting {
            get {
                return ResourceManager.GetString("General_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import plots.
        /// </summary>
        public static string General_ImportPlots {
            get {
                return ResourceManager.GetString("General_ImportPlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included deleted.
        /// </summary>
        public static string General_IncludeDeleted {
            get {
                return ResourceManager.GetString("General_IncludeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string General_InProgress {
            get {
                return ResourceManager.GetString("General_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string General_Keyword {
            get {
                return ResourceManager.GetString("General_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changed.
        /// </summary>
        public static string General_LastChanged {
            get {
                return ResourceManager.GetString("General_LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string General_LastName {
            get {
                return ResourceManager.GetString("General_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string General_Login {
            get {
                return ResourceManager.GetString("General_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly collection activity.
        /// </summary>
        public static string General_MonthlyActivity {
            get {
                return ResourceManager.GetString("General_MonthlyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string General_NotStarted {
            get {
                return ResourceManager.GetString("General_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s password has been reset..
        /// </summary>
        public static string General_PasswordReset {
            get {
                return ResourceManager.GetString("General_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew information.
        /// </summary>
        public static string General_PeopleData {
            get {
                return ResourceManager.GetString("General_PeopleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo information.
        /// </summary>
        public static string General_PhotoData {
            get {
                return ResourceManager.GetString("General_PhotoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot information.
        /// </summary>
        public static string General_PlotData {
            get {
                return ResourceManager.GetString("General_PlotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot collection statistics.
        /// </summary>
        public static string General_PlotMetrics {
            get {
                return ResourceManager.GetString("General_PlotMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot name keyword.
        /// </summary>
        public static string General_PlotNameKeyword {
            get {
                return ResourceManager.GetString("General_PlotNameKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot summary.
        /// </summary>
        public static string General_PlotSummary {
            get {
                return ResourceManager.GetString("General_PlotSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot type.
        /// </summary>
        public static string General_PlotTypeCode {
            get {
                return ResourceManager.GetString("General_PlotTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project information.
        /// </summary>
        public static string General_ProjectData {
            get {
                return ResourceManager.GetString("General_ProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project date.
        /// </summary>
        public static string General_ProjectDate {
            get {
                return ResourceManager.GetString("General_ProjectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has been deleted..
        /// </summary>
        public static string General_ProjectDeleted {
            get {
                return ResourceManager.GetString("General_ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string General_ProjectName {
            get {
                return ResourceManager.GetString("General_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project information has been saved..
        /// </summary>
        public static string General_ProjectSaved {
            get {
                return ResourceManager.GetString("General_ProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string General_ResetPassword {
            get {
                return ResourceManager.GetString("General_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string General_Search {
            get {
                return ResourceManager.GetString("General_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string General_SearchResults {
            get {
                return ResourceManager.GetString("General_SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string General_SignIn {
            get {
                return ResourceManager.GetString("General_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small tree information.
        /// </summary>
        public static string General_SmallTreeData {
            get {
                return ResourceManager.GetString("General_SmallTreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small tree tally information.
        /// </summary>
        public static string General_SmallTreeTallyData {
            get {
                return ResourceManager.GetString("General_SmallTreeTallyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil information.
        /// </summary>
        public static string General_SoilData {
            get {
                return ResourceManager.GetString("General_SoilData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string General_StartDate {
            get {
                return ResourceManager.GetString("General_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string General_Status {
            get {
                return ResourceManager.GetString("General_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stem map information.
        /// </summary>
        public static string General_StemMapData {
            get {
                return ResourceManager.GetString("General_StemMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree information.
        /// </summary>
        public static string General_TreeData {
            get {
                return ResourceManager.GetString("General_TreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of trees.
        /// </summary>
        public static string General_TreeList {
            get {
                return ResourceManager.GetString("General_TreeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been deleted..
        /// </summary>
        public static string General_UserDeleted {
            get {
                return ResourceManager.GetString("General_UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string General_Username {
            get {
                return ResourceManager.GetString("General_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user information has been saved..
        /// </summary>
        public static string General_UserSaved {
            get {
                return ResourceManager.GetString("General_UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string General_UserStatus {
            get {
                return ResourceManager.GetString("General_UserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetation census information.
        /// </summary>
        public static string General_VegetationCensuseData {
            get {
                return ResourceManager.GetString("General_VegetationCensuseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetation information.
        /// </summary>
        public static string General_VegetationData {
            get {
                return ResourceManager.GetString("General_VegetationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor code.
        /// </summary>
        public static string General_VendorCode {
            get {
                return ResourceManager.GetString("General_VendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor has been deleted..
        /// </summary>
        public static string General_VendorDeleted {
            get {
                return ResourceManager.GetString("General_VendorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor name.
        /// </summary>
        public static string General_VendorName {
            get {
                return ResourceManager.GetString("General_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor information has been updated..
        /// </summary>
        public static string General_VendorSaved {
            get {
                return ResourceManager.GetString("General_VendorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor status.
        /// </summary>
        public static string General_VendorStatus {
            get {
                return ResourceManager.GetString("General_VendorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string General_VsnDataTableEmpty {
            get {
                return ResourceManager.GetString("General_VsnDataTableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Type.
        /// </summary>
        public static string General_VsnMeasureTypeCode {
            get {
                return ResourceManager.GetString("General_VsnMeasureTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Year.
        /// </summary>
        public static string General_VsnMeasureYear {
            get {
                return ResourceManager.GetString("General_VsnMeasureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSN Plot Name.
        /// </summary>
        public static string General_VsnPlotName {
            get {
                return ResourceManager.GetString("General_VsnPlotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSN Plot names (comma separated).
        /// </summary>
        public static string General_VsnPlotNames {
            get {
                return ResourceManager.GetString("General_VsnPlotNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string General_VsnPlotOverviewDate {
            get {
                return ResourceManager.GetString("General_VsnPlotOverviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Type.
        /// </summary>
        public static string General_VsnPlotTypeCode {
            get {
                return ResourceManager.GetString("General_VsnPlotTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSN Project ID.
        /// </summary>
        public static string General_VsnProjectId {
            get {
                return ResourceManager.GetString("General_VsnProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSN Table.
        /// </summary>
        public static string General_VsnTableName {
            get {
                return ResourceManager.GetString("General_VsnTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string General_Year {
            get {
                return ResourceManager.GetString("General_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Plots.
        /// </summary>
        public static string Menu_Plots {
            get {
                return ResourceManager.GetString("Menu_Plots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Menu_Projects {
            get {
                return ResourceManager.GetString("Menu_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Menu_Vendors {
            get {
                return ResourceManager.GetString("Menu_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Pages_Dashboard_Title {
            get {
                return ResourceManager.GetString("Pages_Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import project plots.
        /// </summary>
        public static string Pages_Plots_ImportPlots_Title {
            get {
                return ResourceManager.GetString("Pages_Plots_ImportPlots_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage plots.
        /// </summary>
        public static string Pages_Plots_ManagePlots_Title {
            get {
                return ResourceManager.GetString("Pages_Plots_ManagePlots_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View plot details.
        /// </summary>
        public static string Pages_Plots_ViewPlot_Title {
            get {
                return ResourceManager.GetString("Pages_Plots_ViewPlot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string Pages_Projects_AddProject_Title {
            get {
                return ResourceManager.GetString("Pages_Projects_AddProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a project for multiple vendors.
        /// </summary>
        public static string Pages_Projects_AddProjects_Title {
            get {
                return ResourceManager.GetString("Pages_Projects_AddProjects_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string Pages_Projects_EditProject_Title {
            get {
                return ResourceManager.GetString("Pages_Projects_EditProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage projects.
        /// </summary>
        public static string Pages_Projects_ManageProjects_Title {
            get {
                return ResourceManager.GetString("Pages_Projects_ManageProjects_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string Pages_Reports_DownloadTable_Title {
            get {
                return ResourceManager.GetString("Pages_Reports_DownloadTable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user.
        /// </summary>
        public static string Pages_Users_AddUser_Title {
            get {
                return ResourceManager.GetString("Pages_Users_AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a user.
        /// </summary>
        public static string Pages_Users_EditUser_Title {
            get {
                return ResourceManager.GetString("Pages_Users_EditUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string Pages_Users_ManageUsers_Title {
            get {
                return ResourceManager.GetString("Pages_Users_ManageUsers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset user password.
        /// </summary>
        public static string Pages_Users_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Pages_Users_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new vendor.
        /// </summary>
        public static string Pages_Vendors_AddVendor_Title {
            get {
                return ResourceManager.GetString("Pages_Vendors_AddVendor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vendor.
        /// </summary>
        public static string Pages_Vendors_EditVendor_Title {
            get {
                return ResourceManager.GetString("Pages_Vendors_EditVendor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage vendors.
        /// </summary>
        public static string Pages_Vendors_ManageVendors_Title {
            get {
                return ResourceManager.GetString("Pages_Vendors_ManageVendors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a keyword.
        /// </summary>
        public static string Placeholder_Keyword {
            get {
                return ResourceManager.GetString("Placeholder_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: 2022.
        /// </summary>
        public static string Placeholder_Year {
            get {
                return ResourceManager.GetString("Placeholder_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string UserStatusType_Active {
            get {
                return ResourceManager.GetString("UserStatusType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string UserStatusType_Blocked {
            get {
                return ResourceManager.GetString("UserStatusType_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string VendorStatusType_Active {
            get {
                return ResourceManager.GetString("VendorStatusType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string VendorStatusType_Blocked {
            get {
                return ResourceManager.GetString("VendorStatusType_Blocked", resourceCulture);
            }
        }
    }
}
